### ISSUE TITLE
Cflag ERROR when installing

### ISSUE THREAD

**Issue by redreamality** [spacy-io/preshed#2]
the debug info is as belows, is it possible to comment the cflag parts?

  Using cached preshed-0.41.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
.....\setup.py",line 22, in rm_cflag
        cflags = distutils.sysconfig._config_vars['CFLAGS']
    KeyError: 'CFLAGS'

**Comment by honnibal** [comment]
Sure — this can be changed to .get() instead.

What platform are you on, though? I didn't think I'd get a KeyError there.

**Comment by maxirmx** [comment]
Using $CFLAGS is gmake convention. Normally you cannot expect it on Windows even with MinGW. 
I put a Windows-safe version to maxirmx branch though if compiler options are important they have to be enforced for all possible set up options.
